# Statistika və Machine Learning

## Kitabxanaların və datanın yüklənməsi

In [2]:
from common import *
from db import get_engine
engine = get_engine()

In [3]:
ml_df=pd.read_sql_table(
    "flights_clean",
    con=engine,
    schema="silver"
)

ml_df.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DISTANCE,SCHEDULED_DEPARTURE,SCHEDULED_ARRIVAL,DEPARTURE_DELAY,...,WEATHER_SURFACE_PRESSURE,WEATHER_WIND_DIRECTION,WEATHER_SNOWFALL,WEATHER_WIND_GUSTS,YEAR,IS_DELAYED,FLIGHT_STATUS,IS_WEEKEND,DEPARTURE_PERIOD,IS_LONG_DISTANCE
0,October,15,4,B6,SJU,FLL,1046,12:33:00,15:12:00,0.0,...,1015.299988,90.0,0.0,20.200001,2015,0.0,Completed,0,Afternoon,0
1,January,10,6,DL,ATL,MDW,591,10:25:00,11:28:00,-3.0,...,994.400024,341.0,0.0,31.299999,2015,0.0,Completed,1,Morning,0
2,August,21,5,WN,ATL,LAX,1947,08:25:00,10:15:00,-1.0,...,981.200012,319.0,0.0,11.500000,2015,0.0,Completed,0,Morning,1
3,December,3,4,AA,CLT,BOS,728,09:40:00,11:51:00,-4.0,...,990.400024,324.0,0.0,24.100000,2015,0.0,Completed,0,Morning,0
4,July,21,2,WN,LAX,MDW,1750,16:45:00,22:40:00,21.0,...,1008.599976,200.0,0.0,14.000000,2015,0.0,Completed,0,Afternoon,1

In [4]:
ml_df.shape

(999657, 45)

In [3]:
pd.read_sql_table(
    "flights_clean",
    con=engine,
    schema="silver"
)

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DISTANCE,SCHEDULED_DEPARTURE,SCHEDULED_ARRIVAL,DEPARTURE_DELAY,...,WEATHER_SURFACE_PRESSURE,WEATHER_WIND_DIRECTION,WEATHER_SNOWFALL,WEATHER_WIND_GUSTS,YEAR,IS_DELAYED,FLIGHT_STATUS,IS_WEEKEND,DEPARTURE_PERIOD,IS_LONG_DISTANCE
0,October,15,4,B6,SJU,FLL,1046,12:33:00,15:12:00,0.0,...,1015.299988,90.0,0.0,20.200001,2015,0.0,Completed,0,Afternoon,0
1,January,10,6,DL,ATL,MDW,591,10:25:00,11:28:00,-3.0,...,994.400024,341.0,0.0,31.299999,2015,0.0,Completed,1,Morning,0
2,August,21,5,WN,ATL,LAX,1947,08:25:00,10:15:00,-1.0,...,981.200012,319.0,0.0,11.500000,2015,0.0,Completed,0,Morning,1
3,December,3,4,AA,CLT,BOS,728,09:40:00,11:51:00,-4.0,...,990.400024,324.0,0.0,24.100000,2015,0.0,Completed,0,Morning,0
4,July,21,2,WN,LAX,MDW,1750,16:45:00,22:40:00,21.0,...,1008.599976,200.0,0.0,14.000000,2015,0.0,Completed,0,Afternoon,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999652,July,11,6,OO,HLN,DEN,594,07:10:00,08:57:00,-6.0,...,880.400024,215.0,0.0,15.800000,2015,0.0,Completed,1,Morning,0
999653,September,28,1,OO,PHX,DRO,353,08:54:00,11:26:00,-7.0,...,969.400024,315.0,0.0,8.300000,2015,0.0,Completed,0,Morning,0
999654,April,12,7,DL,LGA,FLL,1076,14:54:00,18:13:00,0.0,...,1027.400024,279.0,0.0,16.200001,2015,0.0,Completed,1,Afternoon,0
999655,April,19,7,AA,PHL,MIA,1013,15:55:00,18:53:00,-5.0,...,1023.400024,90.0,0.0,41.000000,2015,0.0,Completed,1,Afternoon,0
999656,March,29,7,UA,BOS,EWR,200,19:26:00,20:53:00,0.0,...,1020.500000,299.0,0.0,16.900000,2015,0.0,Completed,1,Evening,0